import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Abhaya_Libre } from "next/font/google";
import "./globals.css";
import { Italianno } from "next/font/google";
import Header from "./Component/common/Header";
import Footer from "./Component/common/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const abhayaLibre = Abhaya_Libre({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-abhaya",
});

const italianno = Italianno({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${abhayaLibre.variable} ${italianno.className} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
